// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// NOTE: The API keys below are Firebase Web SDK config — they are intentionally
// public. Firebase security is enforced via Security Rules and App Check,
// not by keeping these keys secret. Do NOT confuse with serviceAccountKey.json.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUzNw0FlNVxe4n4MObBMnpt76QFVgDYg',
    appId: '1:574158051421:android:ce64a1e9ec36aef39815b4',
    messagingSenderId: '574158051421',
    projectId: 'greengains-f46f7',
    storageBucket: 'greengains-f46f7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZeyhrg1h66rzQIaX6STPX1D8KORRiYvA',
    appId: '1:574158051421:web:eadc093e8e74b4159815b4',
    messagingSenderId: '574158051421',
    projectId: 'greengains-f46f7',
    authDomain: 'greengains-f46f7.firebaseapp.com',
    storageBucket: 'greengains-f46f7.firebasestorage.app',
    measurementId: 'G-RHCMDR4DWZ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaFrzO2DpWHVSl0b1re0VGxEcgYdYuun8',
    appId: '1:574158051421:ios:9e06804c38b6a5bb9815b4',
    messagingSenderId: '574158051421',
    projectId: 'greengains-f46f7',
    storageBucket: 'greengains-f46f7.firebasestorage.app',
    androidClientId: '574158051421-3bd348lpfs9mlhctfd5267qnath5nuuc.apps.googleusercontent.com',
    iosClientId: '574158051421-4p79ip320llepo9ojq2f4bi8c3a3o4mi.apps.googleusercontent.com',
    iosBundleId: 'com.eremat.greengains',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaFrzO2DpWHVSl0b1re0VGxEcgYdYuun8',
    appId: '1:574158051421:ios:9e06804c38b6a5bb9815b4',
    messagingSenderId: '574158051421',
    projectId: 'greengains-f46f7',
    storageBucket: 'greengains-f46f7.firebasestorage.app',
    androidClientId: '574158051421-3bd348lpfs9mlhctfd5267qnath5nuuc.apps.googleusercontent.com',
    iosClientId: '574158051421-4p79ip320llepo9ojq2f4bi8c3a3o4mi.apps.googleusercontent.com',
    iosBundleId: 'com.eremat.greengains',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZeyhrg1h66rzQIaX6STPX1D8KORRiYvA',
    appId: '1:574158051421:web:eadc093e8e74b4159815b4',
    messagingSenderId: '574158051421',
    projectId: 'greengains-f46f7',
    authDomain: 'greengains-f46f7.firebaseapp.com',
    storageBucket: 'greengains-f46f7.firebasestorage.app',
    measurementId: 'G-RHCMDR4DWZ',
  );

}